[build]
  publish = "public"
  command = """\
    curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    export PATH=/opt/build/repo/dart-sass:$PATH && \
    hugo --gc --minify \
    """
    
[build.environment]
  HUGO_VERSION = "0.142.0"
  HUGO_ENV = "production"
  DART_SASS_VERSION = "1.83.4"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "22"  # Ensure only one version is defined
  GO_VERSION = "1.23.5"
  TZ = "America/New_York"

[context.production.environment]
  HUGO_VERSION = "0.142.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.142.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.142.0"

[dev]
  command = "hugo server"
  port = 8888
  targetPort = 1313

# netlify.toml
[[headers]]
for = "/*"
  [headers.values]
  # Security headers
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "same-origin" # or "strict-origin-when-cross-origin"
  X-Permitted-Cross-Domain-Policies = "none"
  Permissions-Policy = "accelerometer=(self), autoplay=(self), camera=(self), encrypted-media=(self), fullscreen=(self), geolocation=(self), gyroscope=(self), magnetometer=(self), microphone=(self), midi=(self), payment=(self), publickey-credentials-get=(self), sync-xhr=(self), usb=(self), xr-spatial-tracking=(self)"

  # Content-Security-Policy-Report-Only = """
  #   default-src 'none';
  #   style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
  #   img-src 'self' data: https://*.twic.pics https://*.googleusercontent.com https://maps.gstatic.com https://www.facebook.com https://*.facebook.com https://www.gstatic.com;
  #   font-src 'self' https://fonts.gstatic.com;
  #   media-src 'self';
  #   connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://stats.g.doubleclick.net https://www.googletagmanager.com https://www.google.com https://www.recaptcha.net https://www.facebook.com https://graph.facebook.com;
  #   frame-src 'self' https://www.google.com https://www.recaptcha.net;
  #   form-action 'self';
  #   frame-ancestors 'none';
  #   manifest-src 'self';
  #   base-uri 'self';
  # """

  # --- CSP (the plugin will add: 'nonce-…' to script-src at runtime) ---
  # Content-Security-Policy = """
  #   default-src 'none';
  #   style-src 'self' 'unsafe-inline' https:;
  #   img-src 'self' https://*.twic.pics https://*.googleusercontent.com https://maps.gstatic.com https://www.facebook.com https://*.facebook.com https://www.gstatic.com data:;
  #   font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
  #   media-src 'self' https:;
  #   connect-src 'self' https://www.google-analytics.com https://*.analytics.google.com https://stats.g.doubleclick.net https://www.facebook.com https://graph.facebook.com https://www.google.com https://www.recaptcha.net https://www.facebook.com https://graph.facebook.com https:;
  #   frame-src 'self' https://www.google.com https://www.recaptcha.net;
  #   form-action 'self';
  #   frame-ancestors 'none';
  #   manifest-src 'self';
  #   base-uri 'self';
  # """

#    media-src 'self' https: https://res.cloudinary.com/YOUR_CLOUDINARY_CLOUD_NAME/;


[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301
  force = true


# Defunct links

# --- Legacy Spanish paths -> new site ---
[[redirects]]
  from = "/es/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/es/privacy-policy"
  to = "/privacy-policy/"
  status = 301
  force = true

[[redirects]]
  from = "/es/contacto"
  to = "/contact-us/"
  status = 301
  force = true

# --- Services -> new Services hub & pages ---
[[redirects]]
  from = "/services"
  to = "/bahamas-web-design-services/"
  status = 301
  force = true

[[redirects]]
  from = "/services/"
  to = "/bahamas-web-design-services/"
  status = 301
  force = true

[[redirects]]
  from = "/services/website-design"
  to = "/bahamas-web-design-services/website-design-bahamas/"
  status = 301
  force = true

[[redirects]]
  from = "/services/digital-marketing"
  to = "/bahamas-web-design-services/digital-marketing-bahamas/"
  status = 301
  force = true

# (If you ever had a direct SEO page at /services/seo, map it too)
[[redirects]]
  from = "/services/seo"
  to = "/bahamas-web-design-services/seo-bahamas/"
  status = 301
  force = true

# --- Portfolio ---
[[redirects]]
  from = "/work"
  to = "/portfolio/"
  status = 301
  force = true

# Remove old “filter” query-style URLs
[[redirects]]
  from = "/portfolio"
  to = "/portfolio/"
  status = 301
  force = true
  query = { filter = ":any" }

# --- Insights / Blog (old paths & filter URLs) ---
# Send any old Insights index, article slugs, or filter params to the blog hub
# Old filter URLs like /insights?filter=Business (keeps working even if other params exist)
[[redirects]]
  from = "/insights"
  to = "/insights/"
  status = 301
  force = true
  query = { filter = ":any" }


[[redirects]]
  from = "/bahamas-web-design"
  to = "/"
  status = 301
  force = true
